# Generated by Django 3.0.7 on 2020-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_auto_20200718_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
