# Generated by Django 3.0.8 on 2020-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0008_auto_20200723_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('key', models.CharField(max_length=254)),
                ('expiration_date', models.IntegerField()),
            ],
        ),
    ]
