# Generated by Django 3.0.8 on 2020-08-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0009_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
