# Generated by Django 3.0.8 on 2020-08-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0010_auto_20200802_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maker_id',
            field=models.IntegerField(default=0),
        ),
    ]
