# Generated by Django 3.0.8 on 2020-08-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0011_auto_20200802_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
            ],
        ),
    ]
