# Generated by Django 3.0.8 on 2020-08-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0012_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
