# Generated by Django 3.0.8 on 2020-08-07 21:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0013_auto_20200807_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pics_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
