# Generated by Django 3.0.8 on 2020-08-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0016_auto_20200809_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
