# Generated by Django 3.0.8 on 2020-08-17 19:52

from django.db import migrations, models
import webapi.services.uploadToPathAndRename


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0019_auto_20200814_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=webapi.services.uploadToPathAndRename.UploadToPathAndRename('C:\\Users\\1337\\Documents\\WorkSpace\\ecomart\\dev\\api\\ecomartapi\\media\\images')),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
