# Generated by Django 3.0.8 on 2020-09-06 11:08

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import webapi.services.uploadToPathAndRename


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0021_auto_20200818_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=webapi.services.uploadToPathAndRename.UploadToPathAndRename('C:\\Users\\1337\\Documents\\WorkSpace\\ecomart\\dev\\api\\mormadeApi\\media\\images')),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pics_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
