# Generated by Django 3.0.8 on 2020-09-11 11:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0022_auto_20200906_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('author_id', models.IntegerField(default=-1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=1000)),
                ('cover', models.IntegerField(default=None, null=True)),
                ('text', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('author_id', models.IntegerField(default=-1)),
                ('article', models.IntegerField(default=-1)),
                ('type', models.CharField(max_length=255)),
                ('text', models.CharField(default='', max_length=2999)),
                ('image', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
