# Generated by Django 3.0.8 on 2020-09-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0023_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RemoveField(
            model_name='content',
            name='author_id',
        ),
    ]
