# Generated by Django 3.0.8 on 2020-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0024_auto_20200913_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
