# Generated by Django 3.1.1 on 2020-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0029_auto_20201008_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
