# Generated by Django 3.1.1 on 2020-10-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0031_auto_20201010_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(default='', max_length=256),
        ),
    ]
